const slugify = require('slugify')

// function to recreate screenshot urls generated by Cypress default behavior
exports.createScreenshotUrl = (runnable, specName, extra) => {
  let item = runnable
  const nameParts = [runnable.title]
  // Iterate through all parents and grab the titles
  while (item.parent) {
    nameParts.unshift(item.parent.title)
    item = item.parent
  }
  // this is how cypress joins the test title fragments
  const fullTestName = nameParts.filter(Boolean).join(' -- ')
  const filename = slugifyScreenshot(`${fullTestName} ${extra}.png`, extra)

  return `screenshots/${specName}/${filename}`
}

// function to help create deterministic, friendly urls
const slugifyScreenshot = (str, extra) => {
  return slugify(`${str} ${extra}.png`, { lower: true, remove: /[:/]/g })
}

exports.slugifyScreenshot = slugifyScreenshot
