name: Cypress Tests

# This allows you to trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js using the version from .nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn install

      # Run Cypress tests
      - name: Run Cypress Tests
        run: yarn cy:run:test:report

      # Create /docs folder for GitHub Pages
      - name: Create Docs Directory
        run: mkdir -p docs

      # Move the Mochawesome report to /docs so GitHub Pages can serve it
      - name: Move Mochawesome Report to Docs
        run: cp ./cypress/mochawesome/export/mochawesome.html ./docs/index.html

      # Commit the /docs folder with the Mochawesome report
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/index.html
          git commit -m "Deploy mochawesome report to GitHub Pages"
          git push origin main
