name: Cypress Tests

# This allows you to trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js using the version from .nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Install dependencies using Yarn
      - name: Install Dependencies
        run: |
          yarn install
          echo {{vars.APP}}

      # Run Cypress tests
      - name: Run Cypress Tests
        run: yarn cy:run:test:report

      # Deploy the Mochawesome report to GitHub Pages
      - name: Deploy Mochawesome Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          publish_dir: ./cypress/mochawesome/export
